// LoveGo v43 · Management Report Authority + PTMGo Gate
(()=>{
 const wait=()=>{if(typeof sb==='undefined'||typeof S==='undefined'||typeof CLOUD==='undefined'||typeof window.renderAssignments!=='function'){setTimeout(wait,100);return;}install();};
 function install(){if(window.__LOVEGO_V43_GATE__)return;window.__LOVEGO_V43_GATE__=true;
  async function gateRows(){const cyc=CLOUD.cycleMap[S.ui.cycle];if(!cyc)return[];const q=await sb.from('lovego_ptmgo_gate').select('*').eq('cycle_id',cyc.id);if(q.error)throw q.error;return q.data||[];}
  async function authorityRows(){const cyc=CLOUD.cycleMap[S.ui.cycle];if(!cyc)return[];const q=await sb.from('lovego_department_report_context').select('*').eq('cycle_id',cyc.id).eq('authority_resolved',false);if(q.error)throw q.error;return q.data||[];}
  window.setLoveGoReportAuthority=async function(studentId,department,classId){const cyc=CLOUD.cycleMap[S.ui.cycle];if(!cyc||!classId)return;try{const q=await sb.rpc('lovego_set_report_authority',{p_cycle_id:cyc.id,p_student_id:studentId,p_department:department,p_class_id:classId});if(q.error)throw q.error;toast('✓ 本轮报告主班已确定');await cloudPullOperational();renderAssignments();renderProgress();}catch(e){toast('主班保存失败：'+String(e.message||e));}};
  async function authorityBanner(dep){const unresolved=(await authorityRows()).filter(x=>!dep||x.department===dep);if(!unresolved.length)return'';return `<div class="card" style="border-left:5px solid #d39b19"><div class="title">⚠ 同部门多班 · 先选择本轮报告主班</div><div class="meta">每个 Department 每名学生每轮只出 1 份报告。这里处理后才会进入 Teacher Assignment。</div>${unresolved.map(x=>{const st=S.students.find(s=>s.id===x.student_id)||{};const classes=(x.class_ids||[]).map(id=>S.classes.find(c=>c.id===id)).filter(Boolean);return `<div style="margin-top:12px;padding-top:12px;border-top:.5px solid var(--bdr)"><b>${st.name_en||st.name_cn||x.student_id}${st.name_cn&&st.name_en?' · '+st.name_cn:''}</b><div class="meta">${x.department} · ${classes.map(c=>c.display_name||c.class_name).join(' + ')}</div><div style="display:flex;gap:8px;margin-top:7px"><select id="authority_${x.student_id}_${x.department}" style="flex:1"><option value="">— 选择本轮报告主班 —</option>${classes.map(c=>`<option value="${c.id}">${c.display_name||c.class_name}</option>`).join('')}</select><button class="primary" onclick="setLoveGoReportAuthority('${x.student_id}','${x.department}',document.getElementById('authority_${x.student_id}_${x.department}').value)">确定主班</button></div></div>`}).join('')}</div>`;}
  const oldAssign=window.renderAssignments;window.renderAssignments=async function(){const out=await oldAssign.apply(this,arguments);try{const root=document.getElementById('assignList');if(root){const dep=document.getElementById('assignDept')?.value||S.ui.dept;const b=await authorityBanner(dep);if(b)root.insertAdjacentHTML('afterbegin',b);}}catch(e){console.warn(e);}return out;};
  const oldProgress=window.renderProgress;window.renderProgress=async function(){const out=await oldProgress.apply(this,arguments);if(!isAdmin())return out;try{const root=document.getElementById('progressBody');if(!root)return out;const rows=await gateRows(),ready=rows.filter(x=>x.ready_for_ptmgo).length,blocked=rows.length-ready;const labels={REPORT_AUTHORITY_REQUIRED:'主班待决定',ASSIGNMENT_REQUIRED:'老师待分配',ASSIGNMENT_INCOMPLETE:'Assignment 未完整',TEACHER_REVIEW_PENDING:'老师 Review 待完成',READY:'Ready for PTMGo'};const counts={};rows.forEach(x=>counts[x.gate_status]=(counts[x.gate_status]||0)+1);const gate=`<div class="card" style="border-left:5px solid var(--layer);margin-bottom:12px"><div class="title">PTMGo Gate</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:7px"><span class="badge done">${ready} Ready</span><span class="badge">${blocked} Blocked</span>${Object.entries(counts).map(([k,v])=>`<span class="badge ${k==='READY'?'done':''}">${labels[k]||k} · ${v}</span>`).join('')}</div><div class="meta" style="margin-top:7px">只有 Report Authority 已确定、Assignment 合规、当前负责老师全部提交后，才进入 PTMGo 正式报告。</div></div>`;root.insertAdjacentHTML('afterbegin',gate);}catch(e){console.warn(e);}return out;};
 }
 wait();
})();